// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NecroFinances.Infrastructure.Persistence;

#nullable disable

namespace NecroFinances.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505140756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NecroFinances.Application.Models.FinanciamentoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NomeFinanciamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PatrimonioId")
                        .HasColumnType("bigint");

                    b.Property<double>("ValorFinanciamento")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("PatrimonioId");

                    b.ToTable("Financiamentos", (string)null);
                });

            modelBuilder.Entity("NecroFinances.Application.Models.GastosModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataGasto")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataGasto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Icone");

                    b.Property<int>("Parcela")
                        .HasColumnType("int")
                        .HasColumnName("Parcela");

                    b.Property<long>("Serie")
                        .HasColumnType("bigint")
                        .HasColumnName("Serie");

                    b.Property<int>("TipoGasto")
                        .HasColumnType("int")
                        .HasColumnName("TipoGasto");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("int")
                        .HasColumnName("TotalParcelas");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.InvestimentoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NomeInvestimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PatrimonioId")
                        .HasColumnType("bigint");

                    b.Property<double>("ValorInvestimento")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("PatrimonioId");

                    b.ToTable("Investimentos", (string)null);
                });

            modelBuilder.Entity("NecroFinances.Application.Models.MesModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<int>("DiasUteis")
                        .HasColumnType("int")
                        .HasColumnName("DiasUteis");

                    b.Property<int>("HorasExtras")
                        .HasColumnType("int")
                        .HasColumnName("HorasExtras");

                    b.Property<int>("HorasUteis")
                        .HasColumnType("int")
                        .HasColumnName("HorasUteis");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("Meses");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.PatrimonioModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Patrimonios", (string)null);
                });

            modelBuilder.Entity("NecroFinances.Application.Models.PropriedadeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NomePropriedade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PatrimonioId")
                        .HasColumnType("bigint");

                    b.Property<double>("ValorPropriedade")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("PatrimonioId");

                    b.ToTable("Propriedades", (string)null);
                });

            modelBuilder.Entity("NecroFinances.Application.Models.SettingsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<double>("DesafioGastos")
                        .HasColumnType("double")
                        .HasColumnName("DesafioGastos");

                    b.Property<double>("PercentagemTaxaCooperativa")
                        .HasColumnType("double")
                        .HasColumnName("PercentagemTaxaCooperativa");

                    b.Property<double>("PercentagemTaxaINSS")
                        .HasColumnType("double")
                        .HasColumnName("PercentagemTaxaINSS");

                    b.Property<double>("SalarioMinimo")
                        .HasColumnType("double")
                        .HasColumnName("SalarioMinimo");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<double>("ValorHora")
                        .HasColumnType("double")
                        .HasColumnName("ValorHora");

                    b.Property<double>("ValorPlanoDental")
                        .HasColumnType("double")
                        .HasColumnName("ValorPlanoDental");

                    b.Property<double>("ValorPlanoSaude")
                        .HasColumnType("double")
                        .HasColumnName("ValorPlanoSaude");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.UserModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RefreshTokenExpiryTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Username");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.FinanciamentoModel", b =>
                {
                    b.HasOne("NecroFinances.Application.Models.PatrimonioModel", "Patrimonio")
                        .WithMany("Financiamentos")
                        .HasForeignKey("PatrimonioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patrimonio");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.InvestimentoModel", b =>
                {
                    b.HasOne("NecroFinances.Application.Models.PatrimonioModel", "Patrimonio")
                        .WithMany("Investimentos")
                        .HasForeignKey("PatrimonioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patrimonio");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.PropriedadeModel", b =>
                {
                    b.HasOne("NecroFinances.Application.Models.PatrimonioModel", "Patrimonio")
                        .WithMany("Propriedades")
                        .HasForeignKey("PatrimonioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patrimonio");
                });

            modelBuilder.Entity("NecroFinances.Application.Models.PatrimonioModel", b =>
                {
                    b.Navigation("Financiamentos");

                    b.Navigation("Investimentos");

                    b.Navigation("Propriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
